packages:
  - path: "github.com/habitat-network/habitat/core/api"
    output_path: "frontend/types/api.ts"
    exclude_files:
      - habitat_db.go
    frontmatter: |
      import * as node from "./node"
    type_mappings:
      node.State: "node.State"
      node.AppInstallation: "node.AppInstallation"
      node.ReverseProxyRule: "node.ReverseProxyRule"
  - path: "github.com/habitat-network/habitat/core/state/node"
    output_path: "frontend/types/node.ts"
    include_files:
      - schema.go
      - core.go
      - app_installation.go
      - process.go
      - reverse_proxy.go
